spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/sys?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
      username: root
      password: pwd@56
      driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true

